import type { MockBackend } from './backend';
import { emptyDb, type Db, type RecipeRow, type RestaurantRow, type UserRow } from './db';
import { applyStatement } from './services/profile';
import { createInvite } from './services/party';
import { logFood } from './services/life';
import { setFeedback } from './services/recipes';

/** Demo sign-ins shown on the login page in stub mode. */
export const DEMO_ACCOUNTS = [
  { email: 'alex@tastepilot.dev', password: 'tastepilot', name: 'Alex Rivera' },
  { email: 'jordan@tastepilot.dev', password: 'tastepilot', name: 'Jordan Rivera' },
] as const;

type RecipeSeed = Omit<RecipeRow, 'published' | 'createdAt' | 'servings'> & {
  servings?: number;
  ageDays?: number;
};

const CATALOG: RecipeSeed[] = [
  {
    id: 'thai-basil-chicken',
    title: 'Thai Basil Chicken',
    description:
      'Pad krapow: fiery, garlicky stir-fried chicken with holy basil over jasmine rice.',
    cuisine: 'thai',
    tags: ['dinner', 'quick', 'stir-fry'],
    flavors: ['spicy', 'herby', 'savory'],
    timeMinutes: 20,
    emoji: '🌶️',
    color: '#fecaca',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '500 g chicken thighs',
      '5 garlic cloves',
      '4 bird eye chili',
      '1 cup thai basil',
      '1 tbsp fish sauce',
      '1 tbsp light soy sauce',
      '1 tsp sugar',
      'jasmine rice',
    ],
    steps: [
      'Pound the garlic and chili into a rough paste.',
      'Stir-fry the paste in hot oil for 30 seconds, then add the chicken.',
      'Season with fish sauce, soy sauce and sugar.',
      'Toss through the basil off the heat and serve over rice.',
    ],
    baseRating: { average: 4.7, count: 212 },
  },
  {
    id: 'green-curry',
    title: 'Green Curry with Vegetables',
    description: 'Silky coconut green curry with eggplant, bell pepper and Thai basil.',
    cuisine: 'thai',
    tags: ['dinner', 'one-pot', 'vegetarian'],
    flavors: ['spicy', 'creamy', 'herby'],
    timeMinutes: 35,
    emoji: '🍛',
    color: '#bbf7d0',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '3 tbsp green curry paste',
      '400 ml coconut milk',
      '1 eggplant',
      '1 bell pepper',
      '200 g firm tofu',
      'thai basil',
      'lime',
      'jasmine rice',
    ],
    steps: [
      'Fry the curry paste in a splash of coconut cream until fragrant.',
      'Add the rest of the coconut milk and simmer.',
      'Add vegetables and tofu; cook until tender.',
      'Finish with basil and lime.',
    ],
    baseRating: { average: 4.5, count: 140 },
  },
  {
    id: 'pad-thai',
    title: 'Shrimp Pad Thai',
    description: 'Street-style rice noodles with shrimp, egg, tamarind and crushed peanuts.',
    cuisine: 'thai',
    tags: ['dinner', 'stir-fry'],
    flavors: ['sweet', 'sour', 'savory'],
    timeMinutes: 30,
    emoji: '🍜',
    color: '#fed7aa',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '200 g rice noodles',
      '250 g shrimp',
      '2 eggs',
      '3 tbsp tamarind paste',
      '2 tbsp fish sauce',
      '1 tbsp palm sugar',
      '1/2 cup roasted peanuts',
      'scallions',
      'lime',
    ],
    steps: [
      'Soak the noodles until pliable.',
      'Stir-fry shrimp, push aside and scramble the eggs.',
      'Add noodles and sauce; toss until glossy.',
      'Top with peanuts, scallions and lime.',
    ],
    baseRating: { average: 4.6, count: 305 },
  },
  {
    id: 'margherita-pizza',
    title: 'Margherita Pizza',
    description: 'Blistered crust, bright tomato and fresh mozzarella with basil.',
    cuisine: 'italian',
    tags: ['dinner', 'vegetarian', 'baking'],
    flavors: ['savory', 'herby'],
    timeMinutes: 45,
    emoji: '🍕',
    color: '#fde68a',
    source: 'catalog',
    authorId: null,
    ingredients: [
      'pizza dough',
      '1 cup crushed tomatoes',
      '200 g fresh mozzarella',
      'fresh basil',
      'olive oil',
      'salt',
    ],
    steps: [
      'Heat the oven as hot as it goes.',
      'Stretch the dough and spread with tomatoes.',
      'Top with mozzarella and bake until blistered.',
      'Finish with basil and olive oil.',
    ],
    baseRating: { average: 4.4, count: 260 },
  },
  {
    id: 'mushroom-risotto',
    title: 'Mushroom Risotto',
    description: 'Creamy arborio rice with browned mushrooms, white wine and parmesan.',
    cuisine: 'italian',
    tags: ['dinner', 'vegetarian'],
    flavors: ['umami', 'creamy', 'rich'],
    timeMinutes: 40,
    emoji: '🍄',
    color: '#e7e5e4',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '300 g arborio rice',
      '400 g cremini mushrooms',
      '1 shallot',
      '1/2 cup dry white wine',
      '1 l vegetable stock',
      '2 tbsp butter',
      '1/2 cup parmesan',
    ],
    steps: [
      'Brown the mushrooms hard; set aside.',
      'Soften the shallot, toast the rice, then add wine.',
      'Add stock a ladle at a time, stirring, for 18 minutes.',
      'Beat in butter, parmesan and the mushrooms.',
    ],
    baseRating: { average: 4.5, count: 180 },
  },
  {
    id: 'pesto-pasta',
    title: 'Basil Pesto Pasta',
    description: 'Linguine tossed with homemade basil pesto, pine nuts and parmesan.',
    cuisine: 'italian',
    tags: ['dinner', 'quick', 'vegetarian'],
    flavors: ['herby', 'rich'],
    timeMinutes: 20,
    emoji: '🌿',
    color: '#bbf7d0',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '300 g linguine',
      '2 cups fresh basil',
      '1/3 cup pine nuts',
      '1/2 cup parmesan',
      '1 garlic clove',
      'extra virgin olive oil',
    ],
    steps: [
      'Blitz basil, pine nuts, garlic and parmesan with olive oil.',
      'Cook the pasta; reserve some water.',
      'Toss together, loosening with pasta water.',
    ],
    baseRating: { average: 4.6, count: 190 },
  },
  {
    id: 'black-bean-tacos',
    title: 'Smoky Black Bean Tacos',
    description: 'Charred corn tortillas with cumin-spiced black beans, avocado and pickled onion.',
    cuisine: 'mexican',
    tags: ['dinner', 'quick', 'vegetarian', 'vegan'],
    flavors: ['smoky', 'spicy', 'fresh'],
    timeMinutes: 20,
    emoji: '🌮',
    color: '#fde68a',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '8 corn tortillas',
      '2 cans black beans',
      '1 tsp smoked paprika',
      '1 tsp ground cumin',
      '1 avocado',
      '1 red onion',
      'lime',
      'jalapeno',
    ],
    steps: [
      'Warm beans with paprika and cumin; mash a little.',
      'Quick-pickle the onion in lime juice.',
      'Char tortillas and fill.',
    ],
    baseRating: { average: 4.3, count: 98 },
  },
  {
    id: 'chicken-tinga',
    title: 'Chicken Tinga',
    description: 'Shredded chicken in a smoky chipotle-tomato sauce, great in tostadas.',
    cuisine: 'mexican',
    tags: ['dinner', 'make-ahead'],
    flavors: ['smoky', 'spicy'],
    timeMinutes: 45,
    emoji: '🫔',
    color: '#fecaca',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '600 g chicken breast',
      '1 can crushed tomatoes',
      '2 chipotles in adobo',
      '1 onion',
      '2 garlic cloves',
      'dried oregano',
      'corn tortillas',
      'sour cream',
    ],
    steps: [
      'Poach and shred the chicken.',
      'Blend tomatoes, chipotles, onion and garlic.',
      'Simmer the sauce, then fold in the chicken.',
      'Serve on tortillas with sour cream.',
    ],
    baseRating: { average: 4.4, count: 75 },
  },
  {
    id: 'chana-masala',
    title: 'Chana Masala',
    description: 'Chickpeas simmered in a tangy, warmly spiced tomato-onion gravy.',
    cuisine: 'indian',
    tags: ['dinner', 'vegetarian', 'vegan', 'one-pot'],
    flavors: ['spicy', 'savory'],
    timeMinutes: 35,
    emoji: '🫘',
    color: '#fed7aa',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '2 cans chickpeas',
      '1 onion',
      '1 can crushed tomatoes',
      '1 tbsp fresh ginger',
      '3 garlic cloves',
      '2 tsp garam masala',
      '1 tsp turmeric',
      'cilantro',
      'basmati rice',
    ],
    steps: [
      'Brown the onion deeply.',
      'Add ginger, garlic and spices.',
      'Add tomatoes and chickpeas; simmer 20 minutes.',
      'Finish with cilantro; serve with rice.',
    ],
    baseRating: { average: 4.6, count: 156 },
  },
  {
    id: 'butter-chicken',
    title: 'Butter Chicken',
    description: 'Tandoori-style chicken in a velvety tomato, butter and cream sauce.',
    cuisine: 'indian',
    tags: ['dinner'],
    flavors: ['creamy', 'rich', 'spicy'],
    timeMinutes: 50,
    emoji: '🍗',
    color: '#fed7aa',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '700 g chicken thighs',
      '1 cup greek yogurt',
      '3 tbsp butter',
      '1 can crushed tomatoes',
      '1/2 cup heavy cream',
      '1 tbsp fresh ginger',
      '3 garlic cloves',
      '2 tsp garam masala',
      '1/4 cup cashews',
    ],
    steps: [
      'Marinate chicken in yogurt and spices.',
      'Sear the chicken.',
      'Simmer tomatoes, butter, ginger, garlic and blended cashews.',
      'Add cream and the chicken.',
    ],
    baseRating: { average: 4.8, count: 410 },
  },
  {
    id: 'salmon-teriyaki',
    title: 'Salmon Teriyaki Bowl',
    description: 'Glazed salmon over sushi rice with cucumber, avocado and sesame.',
    cuisine: 'japanese',
    tags: ['dinner', 'quick'],
    flavors: ['sweet', 'umami'],
    timeMinutes: 25,
    emoji: '🍣',
    color: '#fbcfe8',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '2 salmon fillets',
      '3 tbsp soy sauce',
      '1 tbsp honey',
      '1 tbsp rice vinegar',
      'sushi rice',
      '1 cucumber',
      '1 avocado',
      'sesame seeds',
    ],
    steps: [
      'Simmer soy, honey and vinegar into a glaze.',
      'Sear salmon and brush with glaze.',
      'Build bowls over rice with cucumber and avocado.',
      'Sprinkle with sesame.',
    ],
    baseRating: { average: 4.5, count: 133 },
  },
  {
    id: 'miso-soup',
    title: 'Miso Soup with Tofu',
    description: 'A soothing bowl of dashi, white miso, silken tofu and scallions.',
    cuisine: 'japanese',
    tags: ['lunch', 'quick'],
    flavors: ['umami'],
    timeMinutes: 15,
    emoji: '🥣',
    color: '#e7e5e4',
    source: 'catalog',
    authorId: null,
    ingredients: ['4 cups dashi', '3 tbsp white miso', '200 g silken tofu', 'scallions', 'wakame'],
    steps: [
      'Warm the dashi without boiling.',
      'Whisk in the miso.',
      'Add tofu and wakame; finish with scallions.',
    ],
    baseRating: { average: 4.2, count: 64 },
  },
  {
    id: 'bibimbap',
    title: 'Bibimbap',
    description: 'Rice bowl with seasoned vegetables, beef, a fried egg and gochujang.',
    cuisine: 'korean',
    tags: ['dinner'],
    flavors: ['spicy', 'savory', 'umami'],
    timeMinutes: 45,
    emoji: '🍚',
    color: '#fecaca',
    source: 'catalog',
    authorId: null,
    ingredients: [
      'rice',
      '200 g ground beef',
      '2 cups spinach',
      '2 carrots',
      '1 zucchini',
      '4 eggs',
      '2 tbsp gochujang',
      '1 tbsp toasted sesame oil',
    ],
    steps: [
      'Cook rice; sauté each vegetable separately.',
      'Brown the beef.',
      'Fry the eggs.',
      'Assemble with gochujang and sesame oil.',
    ],
    baseRating: { average: 4.6, count: 120 },
  },
  {
    id: 'kimchi-fried-rice',
    title: 'Kimchi Fried Rice',
    description: 'Day-old rice fried with funky kimchi, scallions and a runny egg.',
    cuisine: 'korean',
    tags: ['dinner', 'quick'],
    flavors: ['spicy', 'sour', 'umami'],
    timeMinutes: 15,
    emoji: '🥘',
    color: '#fecaca',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '3 cups cooked rice',
      '1 cup kimchi',
      '2 tbsp kimchi juice',
      'scallions',
      '2 eggs',
      '1 tsp toasted sesame oil',
    ],
    steps: [
      'Fry the kimchi until caramelised.',
      'Add rice and kimchi juice; fry until crisp.',
      'Top with fried eggs and scallions.',
    ],
    baseRating: { average: 4.4, count: 88 },
  },
  {
    id: 'shakshuka',
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced pepper and tomato sauce, with feta.',
    cuisine: 'middle eastern',
    tags: ['breakfast', 'vegetarian', 'one-pot'],
    flavors: ['spicy', 'savory'],
    timeMinutes: 30,
    emoji: '🍳',
    color: '#fecaca',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '1 onion',
      '2 bell peppers',
      '1 can crushed tomatoes',
      '1 tsp ground cumin',
      '1 tsp smoked paprika',
      '6 eggs',
      '1/2 cup feta',
      'parsley',
      'bread',
    ],
    steps: [
      'Soften onion and peppers.',
      'Add spices and tomatoes; simmer until thick.',
      'Make wells and crack in the eggs; cover until set.',
      'Finish with feta and parsley.',
    ],
    baseRating: { average: 4.5, count: 170 },
  },
  {
    id: 'falafel-bowl',
    title: 'Falafel Bowl with Tahini',
    description: 'Crisp baked falafel over herby quinoa with cucumber, tomato and tahini sauce.',
    cuisine: 'middle eastern',
    tags: ['lunch', 'vegetarian', 'vegan'],
    flavors: ['herby', 'fresh'],
    timeMinutes: 40,
    emoji: '🧆',
    color: '#bbf7d0',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '2 cans chickpeas',
      '1 cup parsley',
      '1/2 cup cilantro',
      '3 garlic cloves',
      '1 tsp ground cumin',
      '1 cup quinoa',
      '1 cucumber',
      'cherry tomatoes',
      '1/4 cup tahini',
      'lemon juice',
    ],
    steps: [
      'Blitz chickpeas, herbs, garlic and cumin.',
      'Shape and bake falafel until crisp.',
      'Cook quinoa.',
      'Assemble with vegetables and tahini-lemon sauce.',
    ],
    baseRating: { average: 4.3, count: 91 },
  },
  {
    id: 'greek-salad',
    title: 'Greek Salad',
    description: 'Tomatoes, cucumber, red onion and olives with a slab of feta.',
    cuisine: 'mediterranean',
    tags: ['lunch', 'quick', 'vegetarian'],
    flavors: ['fresh'],
    timeMinutes: 10,
    emoji: '🥗',
    color: '#bbf7d0',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '4 tomatoes',
      '1 cucumber',
      '1 red onion',
      '1/2 cup kalamata olives',
      '200 g feta',
      'dried oregano',
      'extra virgin olive oil',
      'red wine vinegar',
    ],
    steps: [
      'Chop the vegetables into big chunks.',
      'Top with olives and the feta.',
      'Dress with oil, vinegar and oregano.',
    ],
    baseRating: { average: 4.2, count: 77 },
  },
  {
    id: 'lemon-herb-cod',
    title: 'Lemon Herb Cod',
    description: 'Flaky baked cod with lemon, parsley and roasted potatoes.',
    cuisine: 'mediterranean',
    tags: ['dinner', 'sheet-pan'],
    flavors: ['fresh', 'herby'],
    timeMinutes: 30,
    emoji: '🐟',
    color: '#bfdbfe',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '4 cod fillets',
      '600 g potatoes',
      '1 lemon',
      'parsley',
      '3 garlic cloves',
      'olive oil',
      'salt',
      'black pepper',
    ],
    steps: [
      'Roast the potatoes for 15 minutes.',
      'Nestle in the cod with lemon, garlic and oil.',
      'Bake 12 minutes; finish with parsley.',
    ],
    baseRating: { average: 4.3, count: 59 },
  },
  {
    id: 'pho',
    title: 'Beef Pho',
    description: 'Star anise beef broth with rice noodles, herbs and lime.',
    cuisine: 'vietnamese',
    tags: ['dinner', 'make-ahead'],
    flavors: ['herby', 'savory'],
    timeMinutes: 180,
    emoji: '🍲',
    color: '#fed7aa',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '1 kg beef bones',
      '300 g flank steak',
      '1 onion',
      'fresh ginger',
      '4 star anise',
      '2 tbsp fish sauce',
      '400 g rice noodles',
      'thai basil',
      'cilantro',
      'lime',
    ],
    steps: [
      'Char onion and ginger; simmer with bones and spices for hours.',
      'Season with fish sauce.',
      'Pour over noodles and thinly sliced steak.',
      'Serve with herbs and lime.',
    ],
    baseRating: { average: 4.7, count: 98 },
  },
  {
    id: 'mapo-tofu',
    title: 'Mapo Tofu',
    description: 'Silken tofu in a numbing, spicy Sichuan sauce with ground pork.',
    cuisine: 'chinese',
    tags: ['dinner', 'quick'],
    flavors: ['spicy', 'umami'],
    timeMinutes: 25,
    emoji: '🥢',
    color: '#fecaca',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '400 g silken tofu',
      '150 g ground pork',
      '2 tbsp doubanjiang',
      '1 tsp sichuan peppercorns',
      '3 garlic cloves',
      '1 tbsp fresh ginger',
      'scallions',
      '1 tbsp cornstarch',
    ],
    steps: [
      'Brown the pork.',
      'Fry doubanjiang, garlic and ginger.',
      'Add stock and tofu; simmer gently.',
      'Thicken and finish with ground peppercorns and scallions.',
    ],
    baseRating: { average: 4.6, count: 101 },
  },
  {
    id: 'berry-oats',
    title: 'Overnight Berry Oats',
    description: 'Make-ahead oats with berries and maple. Breakfast, sorted.',
    cuisine: 'american',
    tags: ['breakfast', 'make-ahead', 'vegetarian', 'quick'],
    flavors: ['sweet', 'fresh'],
    timeMinutes: 5,
    emoji: '🫐',
    color: '#ddd6fe',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '1 cup rolled oats',
      '1 cup oat milk',
      '1/2 cup greek yogurt',
      '1 cup blueberries',
      '1 tbsp maple syrup',
      'cinnamon',
    ],
    steps: [
      'Stir everything together in a jar.',
      'Refrigerate overnight.',
      'Top with more berries.',
    ],
    baseRating: { average: 4.1, count: 66 },
  },
  {
    id: 'banana-pancakes',
    title: 'Fluffy Banana Pancakes',
    description: 'Weekend pancakes with mashed banana and a little cinnamon.',
    cuisine: 'american',
    tags: ['breakfast', 'vegetarian'],
    flavors: ['sweet'],
    timeMinutes: 25,
    emoji: '🥞',
    color: '#fde68a',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '1 1/2 cups flour',
      '2 tsp baking powder',
      '2 bananas',
      '1 egg',
      '1 cup milk',
      '2 tbsp butter',
      'cinnamon',
      'maple syrup',
    ],
    steps: [
      'Whisk dry ingredients.',
      'Mash banana with egg, milk and melted butter.',
      'Combine and cook on a hot griddle.',
    ],
    baseRating: { average: 4.4, count: 120 },
  },
  {
    id: 'chicken-noodle-soup',
    title: 'Chicken Noodle Soup',
    description: 'The classic: tender chicken, egg noodles and vegetables in a golden broth.',
    cuisine: 'american',
    tags: ['dinner', 'one-pot', 'make-ahead'],
    flavors: ['savory', 'herby'],
    timeMinutes: 50,
    emoji: '🍜',
    color: '#fde68a',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '500 g chicken thighs',
      '2 l chicken stock',
      '2 carrots',
      '2 celery stalks',
      '1 onion',
      '200 g egg noodles',
      'parsley',
    ],
    steps: [
      'Simmer chicken in stock with vegetables.',
      'Shred the chicken.',
      'Cook noodles in the broth.',
      'Finish with parsley.',
    ],
    baseRating: { average: 4.5, count: 140 },
  },
  {
    id: 'mango-sticky-rice',
    title: 'Mango Sticky Rice',
    description: 'Sweet coconut sticky rice with ripe mango and toasted sesame.',
    cuisine: 'thai',
    tags: ['dessert'],
    flavors: ['sweet', 'creamy'],
    timeMinutes: 40,
    emoji: '🥭',
    color: '#fde68a',
    source: 'catalog',
    authorId: null,
    ingredients: [
      '1 cup glutinous rice',
      '1 cup coconut milk',
      '1/4 cup sugar',
      'salt',
      '2 mangoes',
      'sesame seeds',
    ],
    steps: [
      'Steam the soaked rice.',
      'Warm coconut milk with sugar and salt.',
      'Pour over rice and rest.',
      'Serve with mango and sesame.',
    ],
    baseRating: { average: 4.7, count: 115 },
  },
];

const COMMUNITY: RecipeSeed[] = [
  {
    id: 'priya-dal',
    title: "Priya's Weeknight Red Lentil Dal",
    description: 'My go-to after work: red lentils, tempered spices, and a squeeze of lemon.',
    cuisine: 'indian',
    tags: ['dinner', 'vegetarian', 'vegan', 'one-pot'],
    flavors: ['savory', 'spicy'],
    timeMinutes: 30,
    emoji: '🍲',
    color: '#fed7aa',
    source: 'community',
    authorId: 'usr_priya',
    ingredients: [
      '1 cup red lentils',
      '1 onion',
      '3 garlic cloves',
      '1 tbsp fresh ginger',
      '1 tsp turmeric',
      '1 tsp ground cumin',
      '1 can crushed tomatoes',
      'lemon juice',
      'cilantro',
    ],
    steps: [
      'Simmer lentils with turmeric until soft.',
      'Fry onion, garlic, ginger and cumin.',
      'Stir in tomatoes, then the lentils.',
      'Finish with lemon and cilantro.',
    ],
    baseRating: { average: 4.8, count: 42 },
    ageDays: 9,
  },
  {
    id: 'marco-carbonara',
    title: "Marco's Real Carbonara",
    description: 'No cream. Ever. Guanciale (or pancetta), eggs, pecorino, pepper.',
    cuisine: 'italian',
    tags: ['dinner', 'quick'],
    flavors: ['rich', 'savory'],
    timeMinutes: 20,
    emoji: '🍝',
    color: '#fde68a',
    source: 'community',
    authorId: 'usr_marco',
    ingredients: [
      '400 g spaghetti',
      '150 g pancetta',
      '4 egg yolks',
      '1 cup parmesan',
      'black pepper',
    ],
    steps: [
      'Render the pancetta.',
      'Whisk yolks with cheese and lots of pepper.',
      'Toss hot pasta with pancetta, then off the heat with the egg mix and pasta water.',
    ],
    baseRating: { average: 4.9, count: 58 },
    ageDays: 4,
  },
  {
    id: 'lena-gf-bowl',
    title: "Lena's Gluten-Free Harvest Bowl",
    description: 'Roasted sweet potato, kale and quinoa with a maple-tahini drizzle. Celiac-safe.',
    cuisine: 'mediterranean',
    tags: ['lunch', 'vegetarian', 'vegan'],
    flavors: ['sweet', 'fresh'],
    timeMinutes: 35,
    emoji: '🍠',
    color: '#fed7aa',
    source: 'community',
    authorId: 'usr_lena',
    ingredients: [
      '2 sweet potatoes',
      '1 bunch kale',
      '1 cup quinoa',
      '1 can chickpeas',
      '3 tbsp tahini',
      '1 tbsp maple syrup',
      'lemon juice',
      'olive oil',
    ],
    steps: [
      'Roast sweet potato and chickpeas.',
      'Massage kale with lemon and oil.',
      'Cook quinoa.',
      'Drizzle with maple-tahini.',
    ],
    baseRating: { average: 4.6, count: 23 },
    ageDays: 2,
  },
  {
    id: 'jordan-shroom-tacos',
    title: "Jordan's Crispy Mushroom Tacos",
    description: 'Oyster mushrooms roasted until crisp, with lime crema. Vegetarian taco night.',
    cuisine: 'mexican',
    tags: ['dinner', 'vegetarian'],
    flavors: ['smoky', 'umami'],
    timeMinutes: 30,
    emoji: '🍄',
    color: '#e7e5e4',
    source: 'community',
    authorId: 'usr_jordan',
    ingredients: [
      '400 g mushrooms',
      '1 tsp smoked paprika',
      '8 corn tortillas',
      '1/2 cup sour cream',
      'lime',
      'red onion',
      'cilantro',
    ],
    steps: [
      'Tear and roast mushrooms with paprika until crisp.',
      'Mix sour cream with lime.',
      'Fill tortillas; top with onion and cilantro.',
    ],
    baseRating: { average: 4.5, count: 12 },
    ageDays: 6,
  },
];

const RESTAURANTS: RestaurantRow[] = [
  {
    id: 'rest-lotus',
    name: 'Lotus Thai Kitchen',
    cuisine: 'thai',
    neighborhood: 'Riverside',
    priceLevel: 2,
    emoji: '🪷',
    dishes: [
      {
        id: 'd-lotus-1',
        name: 'Pad Krapow Gai',
        description: 'Holy basil chicken, fried egg',
        price: '$15',
        ingredients: [
          'chicken',
          'thai basil',
          'garlic',
          'chili',
          'fish sauce',
          'egg',
          'jasmine rice',
        ],
      },
      {
        id: 'd-lotus-2',
        name: 'Massaman Curry',
        description: 'Slow-cooked beef, potato, peanuts',
        price: '$18',
        ingredients: ['beef', 'potato', 'coconut milk', 'massaman paste', 'peanuts'],
      },
      {
        id: 'd-lotus-3',
        name: 'Tom Yum Soup',
        description: 'Hot and sour with shrimp',
        price: '$12',
        ingredients: ['shrimp', 'lemongrass', 'lime', 'chili', 'mushrooms', 'fish sauce'],
      },
      {
        id: 'd-lotus-4',
        name: 'Papaya Salad',
        description: 'Green papaya, lime, chili',
        price: '$11',
        ingredients: ['green papaya', 'lime', 'chili', 'tomatoes', 'fish sauce', 'peanuts'],
      },
    ],
  },
  {
    id: 'rest-nonna',
    name: "Nonna's Trattoria",
    cuisine: 'italian',
    neighborhood: 'Old Town',
    priceLevel: 3,
    emoji: '🍷',
    dishes: [
      {
        id: 'd-nonna-1',
        name: 'Cacio e Pepe',
        description: 'Pecorino, black pepper',
        price: '$19',
        ingredients: ['spaghetti', 'parmesan', 'black pepper', 'butter'],
      },
      {
        id: 'd-nonna-2',
        name: 'Pesto Trofie',
        description: 'Ligurian pesto, green beans',
        price: '$21',
        ingredients: ['pasta', 'pesto', 'potatoes', 'green beans'],
      },
      {
        id: 'd-nonna-3',
        name: 'Grilled Branzino',
        description: 'Lemon, herbs, olive oil',
        price: '$29',
        ingredients: ['white fish', 'lemon', 'parsley', 'olive oil'],
      },
      {
        id: 'd-nonna-4',
        name: 'House Tiramisu',
        description: 'Mascarpone, espresso, cocoa',
        price: '$10',
        ingredients: ['mascarpone', 'egg', 'sugar', 'ladyfingers', 'espresso', 'cocoa'],
      },
    ],
  },
  {
    id: 'rest-seoul',
    name: 'Seoul Bowl',
    cuisine: 'korean',
    neighborhood: 'Market District',
    priceLevel: 2,
    emoji: '🍲',
    dishes: [
      {
        id: 'd-seoul-1',
        name: 'Dolsot Bibimbap',
        description: 'Stone pot, crispy rice',
        price: '$16',
        ingredients: ['rice', 'beef', 'spinach', 'carrots', 'egg', 'gochujang', 'sesame oil'],
      },
      {
        id: 'd-seoul-2',
        name: 'Kimchi Jjigae',
        description: 'Kimchi and tofu stew',
        price: '$15',
        ingredients: ['kimchi', 'tofu', 'pork belly', 'scallions'],
      },
      {
        id: 'd-seoul-3',
        name: 'Japchae',
        description: 'Glass noodles and vegetables',
        price: '$14',
        ingredients: [
          'sweet potato noodles',
          'spinach',
          'carrots',
          'mushrooms',
          'soy sauce',
          'sesame oil',
        ],
      },
    ],
  },
  {
    id: 'rest-green',
    name: 'Green Fork',
    cuisine: 'mediterranean',
    neighborhood: 'Riverside',
    priceLevel: 2,
    emoji: '🥙',
    dishes: [
      {
        id: 'd-green-1',
        name: 'Falafel Plate',
        description: 'Hummus, tabbouleh, pickles',
        price: '$14',
        ingredients: ['chickpeas', 'parsley', 'garlic', 'tahini', 'lemon', 'bulgur'],
      },
      {
        id: 'd-green-2',
        name: 'Roasted Veg Bowl',
        description: 'Quinoa, sweet potato, kale',
        price: '$15',
        ingredients: ['quinoa', 'sweet potato', 'kale', 'olive oil', 'lemon'],
      },
      {
        id: 'd-green-3',
        name: 'Lentil Soup',
        description: 'Red lentils, cumin, lemon',
        price: '$9',
        ingredients: [
          'red lentils',
          'onion',
          'carrots',
          'ground cumin',
          'lemon juice',
          'olive oil',
        ],
      },
    ],
  },
];

function user(
  b: MockBackend,
  partial: Partial<UserRow> & Pick<UserRow, 'id' | 'name' | 'avatarColor'>,
): UserRow {
  return {
    kind: 'full',
    handle: null,
    email: null,
    password: null,
    bio: '',
    householdId: null,
    liteForPartyId: null,
    deviceIds: [],
    shareTasteWithParties: true,
    createdAt: b.nowIso(),
    ...partial,
  };
}

/** Timestamp `days` ago, for evidence and logs. */
const ago = (b: MockBackend, days: number) =>
  new Date(b.now().getTime() - days * 86_400_000).toISOString();

export function buildSeed(b: MockBackend): Db {
  b.db = emptyDb();
  const db = b.db;

  db.households.push({
    id: 'hh_rivera',
    name: 'Rivera household',
    memberIds: ['usr_alex', 'usr_jordan', 'usr_sam'],
  });
  db.users.push(
    user(b, {
      id: 'usr_alex',
      name: 'Alex Rivera',
      handle: 'alex',
      email: DEMO_ACCOUNTS[0].email,
      password: DEMO_ACCOUNTS[0].password,
      bio: 'Weeknight cook, chili enthusiast.',
      avatarColor: '#c2410c',
      householdId: 'hh_rivera',
      createdAt: ago(b, 60),
    }),
    user(b, {
      id: 'usr_jordan',
      name: 'Jordan Rivera',
      handle: 'jordan',
      email: DEMO_ACCOUNTS[1].email,
      password: DEMO_ACCOUNTS[1].password,
      bio: 'Vegetarian, taco evangelist.',
      avatarColor: '#0f766e',
      householdId: 'hh_rivera',
      createdAt: ago(b, 58),
    }),
    user(b, {
      id: 'usr_sam',
      name: 'Sam Rivera',
      avatarColor: '#7c3aed',
      householdId: 'hh_rivera',
      createdAt: ago(b, 58),
    }),
    user(b, {
      id: 'usr_priya',
      name: 'Priya Shah',
      handle: 'priya',
      bio: 'Home cook. Dal is a love language.',
      avatarColor: '#be185d',
      createdAt: ago(b, 90),
    }),
    user(b, {
      id: 'usr_marco',
      name: 'Marco Bianchi',
      handle: 'marco',
      bio: 'Pasta purist from Bologna.',
      avatarColor: '#1d4ed8',
      createdAt: ago(b, 120),
    }),
    user(b, {
      id: 'usr_lena',
      name: 'Lena Okafor',
      handle: 'lena',
      bio: 'Celiac, gluten-free baker, no compromises.',
      avatarColor: '#4d7c0f',
      shareTasteWithParties: false,
      createdAt: ago(b, 45),
    }),
    user(b, {
      id: 'usr_chris',
      kind: 'lite',
      name: 'Chris',
      avatarColor: '#b45309',
      liteForPartyId: 'pty_friday',
      deviceIds: ['seed-device-chris'],
      createdAt: ago(b, 2),
    }),
  );

  db.recipes.push(
    ...[...CATALOG, ...COMMUNITY].map(({ ageDays, servings, ...r }) => ({
      ...r,
      servings: servings ?? 4,
      published: true,
      createdAt: ago(b, ageDays ?? 200),
    })),
  );
  db.restaurants.push(...RESTAURANTS);

  // Statements in people's own words, parsed by the same rules as the app.
  applyStatement(
    b,
    'usr_alex',
    "I'm allergic to tree nuts. I love spicy food and thai food, but I don't like cilantro.",
    ago(b, 40),
  );
  applyStatement(b, 'usr_jordan', "I'm vegetarian. I love mushrooms and mexican food.", ago(b, 40));
  applyStatement(b, 'usr_sam', 'Sam is allergic to peanuts.', ago(b, 40));
  applyStatement(
    b,
    'usr_priya',
    "I'm allergic to shellfish. I love indian food and spicy food.",
    ago(b, 80),
  );
  applyStatement(b, 'usr_marco', 'I love italian food and parmesan.', ago(b, 100));
  applyStatement(b, 'usr_lena', 'I have celiac disease. I love mediterranean food.', ago(b, 40));
  applyStatement(b, 'usr_chris', "No dairy please, I'm lactose intolerant.", ago(b, 2));

  // Alex's food history: behavioral evidence.
  const log = (
    days: number,
    entry: {
      kind: 'home' | 'restaurant';
      dishName: string;
      recipeId?: string;
      restaurantName?: string;
      ingredients?: string[];
      rating: 'liked' | 'neutral' | 'disliked';
      notes?: string;
    },
  ) =>
    logFood(
      b,
      'usr_alex',
      {
        kind: entry.kind,
        dishName: entry.dishName,
        recipeId: entry.recipeId ?? null,
        restaurantName: entry.restaurantName ?? null,
        ingredients: entry.ingredients ?? [],
        rating: entry.rating,
        notes: entry.notes ?? '',
        eatenOn: b.dateOffset(-days),
      },
      ago(b, days),
    );
  log(21, {
    kind: 'home',
    dishName: 'Mushroom Risotto',
    recipeId: 'mushroom-risotto',
    rating: 'neutral',
    notes: 'Fine, a bit heavy.',
  });
  log(16, {
    kind: 'restaurant',
    dishName: 'Spicy Miso Ramen',
    restaurantName: 'Noodle Bar',
    ingredients: ['ramen noodles', 'miso', 'pork belly', 'chili', 'scallions', 'egg'],
    rating: 'liked',
  });
  log(12, {
    kind: 'home',
    dishName: 'Black Bean Tacos',
    recipeId: 'black-bean-tacos',
    rating: 'liked',
  });
  log(8, {
    kind: 'home',
    dishName: 'Chana Masala',
    recipeId: 'chana-masala',
    rating: 'liked',
    notes: 'Too much cilantro, otherwise great.',
  });
  log(3, {
    kind: 'home',
    dishName: 'Thai Basil Chicken',
    recipeId: 'thai-basil-chicken',
    rating: 'liked',
    notes: 'Doubled the chili.',
  });
  setFeedback(b, 'usr_alex', 'salmon-teriyaki', 'like');

  db.pantry.push(
    ...[
      ['jasmine rice', '2 kg'],
      ['garlic', '1 bulb'],
      ['onions', '3'],
      ['eggs', '6'],
      ['soy sauce', '1 bottle'],
      ['chicken thighs', '500 g'],
      ['thai basil', '1 bunch'],
      ['limes', '4'],
      ['coconut milk', '2 cans'],
      ['spaghetti', '500 g'],
      ['canned tomatoes', '2 cans'],
      ['chickpeas', '2 cans'],
    ].map(([name, quantity], i) => ({
      id: `pan_seed_${i}`,
      userId: 'usr_alex',
      name: name as string,
      quantity: quantity as string,
      addedAt: ago(b, 5),
    })),
  );

  // A Meal Party with a mix of full and lite members.
  db.parties.push({
    id: 'pty_friday',
    name: 'Friday Potluck',
    date: b.dateOffset(5),
    description: 'Backyard potluck at our place. Bring a dish and tell us what you can’t eat!',
    hostId: 'usr_alex',
    createdAt: ago(b, 7),
    updatedAt: ago(b, 2),
  });
  db.memberships.push(
    { partyId: 'pty_friday', userId: 'usr_alex', role: 'host', joinedAt: ago(b, 7) },
    { partyId: 'pty_friday', userId: 'usr_jordan', role: 'member', joinedAt: ago(b, 6) },
    { partyId: 'pty_friday', userId: 'usr_priya', role: 'member', joinedAt: ago(b, 4) },
    { partyId: 'pty_friday', userId: 'usr_chris', role: 'member', joinedAt: ago(b, 2) },
  );
  const groupLink = createInvite(b, 'pty_friday', 'usr_alex', {
    label: 'Group chat',
    maxUses: null,
  });
  createInvite(b, 'pty_friday', 'usr_alex', { label: 'For Lena', maxUses: 1 });
  const groupRow = db.invites.find((i) => i.id === groupLink.id);
  if (groupRow) groupRow.uses = 2;
  // Stable tokens so the demo invite links are easy to try.
  db.invites.forEach(
    (invite, i) => (invite.token = ['friday-group', 'friday-lena'][i] ?? invite.token),
  );

  db.contributions.push(
    {
      id: 'pot_1',
      partyId: 'pty_friday',
      memberId: 'usr_jordan',
      dishName: 'Caprese salad',
      recipeId: null,
      ingredients: ['tomatoes', 'fresh mozzarella', 'basil', 'olive oil', 'balsamic vinegar'],
      course: 'side',
      status: 'claimed',
      createdAt: ago(b, 5),
    },
    {
      id: 'pot_2',
      partyId: 'pty_friday',
      memberId: 'usr_priya',
      dishName: 'Basil Pesto Pasta',
      recipeId: 'pesto-pasta',
      ingredients: [],
      course: 'main',
      status: 'proposed',
      createdAt: ago(b, 3),
    },
    {
      id: 'pot_3',
      partyId: 'pty_friday',
      memberId: 'usr_chris',
      dishName: 'Fruit salad',
      recipeId: null,
      ingredients: ['watermelon', 'strawberries', 'mango', 'mint', 'lime juice'],
      course: 'dessert',
      status: 'claimed',
      createdAt: ago(b, 2),
    },
  );

  // This week's household plan.
  db.calendar.push(
    {
      id: 'cal_1',
      householdId: 'hh_rivera',
      date: b.dateOffset(0),
      slot: 'dinner',
      recipeId: 'black-bean-tacos',
      addedBy: 'usr_jordan',
      createdAt: ago(b, 3),
    },
    {
      id: 'cal_2',
      householdId: 'hh_rivera',
      date: b.dateOffset(1),
      slot: 'dinner',
      recipeId: 'green-curry',
      addedBy: 'usr_alex',
      createdAt: ago(b, 3),
    },
    {
      id: 'cal_3',
      householdId: 'hh_rivera',
      date: b.dateOffset(2),
      slot: 'breakfast',
      recipeId: 'berry-oats',
      addedBy: 'usr_alex',
      createdAt: ago(b, 3),
    },
    {
      id: 'cal_4',
      householdId: 'hh_rivera',
      date: b.dateOffset(3),
      slot: 'dinner',
      recipeId: 'pad-thai',
      addedBy: 'usr_alex',
      createdAt: ago(b, 1),
    },
  );

  db.follows.push(
    { followerId: 'usr_alex', followeeId: 'usr_priya' },
    { followerId: 'usr_alex', followeeId: 'usr_marco' },
    { followerId: 'usr_jordan', followeeId: 'usr_alex' },
    { followerId: 'usr_priya', followeeId: 'usr_lena' },
  );

  db.posts.push(
    {
      id: 'post_1',
      recipeId: 'thai-basil-chicken',
      kind: 'review',
      authorId: 'usr_priya',
      rating: 5,
      body: 'Exactly like the stalls in Bangkok. @alex you have to try it with a crispy fried egg.',
      photoUrl: null,
      createdAt: ago(b, 6),
    },
    {
      id: 'post_2',
      recipeId: 'thai-basil-chicken',
      kind: 'tip',
      authorId: 'usr_marco',
      rating: null,
      body: 'Use a really hot pan and don’t crowd it. The chicken should sizzle, not steam.',
      photoUrl: null,
      createdAt: ago(b, 5),
    },
    {
      id: 'post_3',
      recipeId: 'priya-dal',
      kind: 'comment',
      authorId: 'usr_lena',
      rating: null,
      body: 'Made this for my book club, gone in minutes! Thanks @priya.',
      photoUrl: null,
      createdAt: ago(b, 3),
    },
    {
      id: 'post_4',
      recipeId: 'marco-carbonara',
      kind: 'review',
      authorId: 'usr_alex',
      rating: 5,
      body: 'Finally, carbonara that doesn’t scramble. The off-heat trick works.',
      photoUrl: null,
      createdAt: ago(b, 2),
    },
  );

  return db;
}
